#!/bin/bash

SCRIPT_PATH=$(dirname $0)

CONFIG=$SCRIPT_PATH/config.xml
CHECKSTYLE_VERSION=6.14.1
CHECKSTYLE_JAR="$SCRIPT_PATH/checkstyle-$CHECKSTYLE_VERSION.jar"

if [ ! -s $CHECKSTYLE_JAR ]; then
  DOWNLOAD_URL="https://github.com/checkstyle/checkstyle/releases/download/checkstyle-$CHECKSTYLE_VERSION/checkstyle-$CHECKSTYLE_VERSION-all.jar"
  SOURCES_URL="https://github.com/checkstyle/checkstyle/tree/checkstyle-$CHECKSTYLE_VERSION"

  echo "Downloading the checkstyle jar file at $DOWNLOAD_URL.
  The sources can be found at $SOURCES_URL."

  if ! wget "$DOWNLOAD_URL" -O "$CHECKSTYLE_JAR"; then
    echo "Download failed."
    exit 1
  fi
fi

if [ "$#" -lt 1 ]; then
  echo "No argument provided. Exiting."
  exit 0
fi

java  -jar $CHECKSTYLE_JAR -c $CONFIG "$@"
